# Generated by Django 4.1.3 on 2022-11-28 09:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kursach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkdata',
            name='type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='kursach.typeoftranscation', verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkdata',
            name='date',
            field=models.DateField(default=datetime.date(2022, 11, 28)),
        ),
    ]
