# Generated by Django 4.1.3 on 2022-12-03 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursach', '0002_checkdata_type_alter_checkdata_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='date',
        ),
        migrations.RemoveField(
            model_name='news',
            name='text',
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(default='2'),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.CharField(default='2', max_length=255),
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle',
            field=models.CharField(default='2', max_length=140),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.CharField(default='2', max_length=255),
        ),
        migrations.AlterField(
            model_name='checkdata',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 3)),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='2', max_length=120),
        ),
    ]
