# Generated by Django 4.1.3 on 2022-11-15 17:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kursach', '0010_alter_check_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='check_data',
            name='date',
            field=models.DateField(default=datetime.date(2022, 11, 15)),
        ),
    ]
